version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: florentlee/spread.gl.processing.toolkit:2.0-beta
    ports:
      - "8000:7860"
    environment:
      - PORT=7860

  frontend:
    build:
      context: ./frontend
    image: florentlee/spread.gl.web.page:2.0-beta
    ports:
      - "8080:7860"
    depends_on:
      - backend
