import argparse
from continuous_space_processor import *
from discrete_space_processor import *


def main():
    welcome = "Welcome to this processing tool! You can convert a single phylogenetic tree to an acceptable input file for Spread.gl."
    parser = argparse.ArgumentParser(description=welcome)
    parser.add_argument('--tree', '-t', required=True,
                        help='Specify the file name of your phylogenetic tree with filename extension.')
    parser.add_argument('--date', '-d', choices=['float', 'datetime'], required=True,
                        help='At the end of sequence names, you can typically find the date format. '
                             'If it is a floating-point number, enter "float". '
                             'If it is ISO-8601 (Year-Month-Day/yyyy-mm-dd), enter "datetime". '
                             'When it is incomplete, the first day of the corresponding month or year will be used.')
    parser.add_argument('--location', '-l',
                        help='Optional, only mandatory when processing MCC tree files. '
                             'Enter the two annotations, storing latitudes and longitudes (in this order), with a comma separator. '
                             'If there is only one annotation that stores the location names, enter this annotation without a comma.')
    parser.add_argument('--geoinfo', '-g',
                        help='Optional, only mandatory when processing BEAST single tree files. '
                             'Specify the name of the file containing extra geographic information with filename extension. '
                             'This file should be generated by R script before this step.')
    parser.add_argument('--list', '-li',
                        help='Optional, only mandatory in the case of discrete space. '
                             'Specify the file name of your list of coordinates with filename extension. '
                             'This file should be in the csv format with a comma (",") separator, '
                             'and should be comprised of three columns with a specific header of "location,latitude,longitude".')
    parser.add_argument('--format', '-f',  choices=['csv'],
                        help='Optional: Type in "csv" if you would like to inspect your output file in a tabular format.')

    args = parser.parse_args()
    tree = str(args.tree)
    date = str(args.date)
    location = str(args.location).split(',')
    geo_info = str(args.geoinfo)
    location_list = str(args.list)
    extension = str(args.format)

    if location_list == 'None':
        process_continuous_phylogeography(tree, date, location, geo_info, extension)
    else:
        process_discrete_phylogeography(tree, date, location, geo_info, location_list, extension)


# Run with command line arguments precisely when called directly
# (rather than when imported)
if __name__ == '__main__':
    main()
